// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace HuaweiCloud.DIS.Api.Protobuf {

  /// <summary>Holder for reflection information generated from message.proto</summary>
  public static partial class MessageReflection {

    #region Descriptor
    /// <summary>File descriptor for message.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1tZXNzYWdlLnByb3RvEg9nb29nbGUucHJvdG9idWYiYQoRUHV0UmVjb3Jk",
            "c1JlcXVlc3QSEgoKc3RyZWFtTmFtZRgBIAEoCRI4CgdyZWNvcmRzGAIgAygL",
            "MicuZ29vZ2xlLnByb3RvYnVmLlB1dFJlY29yZHNSZXF1ZXN0RW50cnkiyAEK",
            "FlB1dFJlY29yZHNSZXF1ZXN0RW50cnkSDAoEZGF0YRgDIAEoDBIXCg9leHBs",
            "aWNpdEhhc2hLZXkYBCABKAkSFAoMcGFydGl0aW9uS2V5GAUgASgJEhMKC3Bh",
            "cnRpdGlvbklkGAYgASgJEkkKDGV4dGVuZGVkSW5mbxgHIAEoCzIzLmdvb2ds",
            "ZS5wcm90b2J1Zi5QdXRSZWNvcmRzUmVxdWVzdEVudHJ5RXh0ZW5kZWRJbmZv",
            "EhEKCXRpbWVzdGFtcBgdIAEoAyJuCiJQdXRSZWNvcmRzUmVxdWVzdEVudHJ5",
            "RXh0ZW5kZWRJbmZvEhAKCGZpbGVOYW1lGAggASgJEhUKDWRlbGl2ZXJEYXRh",
            "SWQYCSABKAkSDwoHZW5kRmxhZxgKIAEoCBIOCgZzZXFOdW0YCyABKAMiZgoQ",
            "UHV0UmVjb3Jkc1Jlc3VsdBIZChFmYWlsZWRSZWNvcmRDb3VudBgVIAEoBRI3",
            "CgdyZWNvcmRzGBYgAygLMiYuZ29vZ2xlLnByb3RvYnVmLlB1dFJlY29yZHNS",
            "ZXN1bHRFbnRyeSJpChVQdXRSZWNvcmRzUmVzdWx0RW50cnkSDwoHc2hhcmRJ",
            "ZBgXIAEoCRIWCg5zZXF1ZW5jZU51bWJlchgYIAEoCRIRCgllcnJvckNvZGUY",
            "GSABKAkSFAoMZXJyb3JNZXNzYWdlGBogASgJIjkKEUdldFJlY29yZHNSZXF1",
            "ZXN0EhUKDXNoYXJkSXRlcmF0b3IYDCABKAkSDQoFbGltaXQYDSABKAUiVwoQ",
            "R2V0UmVjb3Jkc1Jlc3VsdBIZChFuZXh0U2hhcmRJdGVyYXRvchgOIAEoCRIo",
            "CgdyZWNvcmRzGBAgAygLMhcuZ29vZ2xlLnByb3RvYnVmLlJlY29yZCJuCgZS",
            "ZWNvcmQSFAoMcGFydGl0aW9uS2V5GBEgASgJEhYKDnNlcXVlbmNlTnVtYmVy",
            "GBIgASgJEgwKBGRhdGEYEyABKAwSEQoJdGltZXN0YW1wGBsgASgDEhUKDXRp",
            "bWVzdGFtcFR5cGUYHCABKAlCH6oCHEh1YXdlaUNsb3VkLkRJUy5BcGkuUHJv",
            "dG9idWZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequest), global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequest.Parser, new[]{ "StreamName", "Records" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry), global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry.Parser, new[]{ "Data", "ExplicitHashKey", "PartitionKey", "PartitionId", "ExtendedInfo", "Timestamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo), global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo.Parser, new[]{ "FileName", "DeliverDataId", "EndFlag", "SeqNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResult), global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResult.Parser, new[]{ "FailedRecordCount", "Records" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry), global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry.Parser, new[]{ "ShardId", "SequenceNumber", "ErrorCode", "ErrorMessage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.GetRecordsRequest), global::HuaweiCloud.DIS.Api.Protobuf.GetRecordsRequest.Parser, new[]{ "ShardIterator", "Limit" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.GetRecordsResult), global::HuaweiCloud.DIS.Api.Protobuf.GetRecordsResult.Parser, new[]{ "NextShardIterator", "Records" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::HuaweiCloud.DIS.Api.Protobuf.Record), global::HuaweiCloud.DIS.Api.Protobuf.Record.Parser, new[]{ "PartitionKey", "SequenceNumber", "Data", "Timestamp", "TimestampType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PutRecordsRequest : pb::IMessage<PutRecordsRequest> {
    private static readonly pb::MessageParser<PutRecordsRequest> _parser = new pb::MessageParser<PutRecordsRequest>(() => new PutRecordsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRecordsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequest(PutRecordsRequest other) : this() {
      streamName_ = other.streamName_;
      records_ = other.records_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequest Clone() {
      return new PutRecordsRequest(this);
    }

    /// <summary>Field number for the "streamName" field.</summary>
    public const int StreamNameFieldNumber = 1;
    private string streamName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StreamName {
      get { return streamName_; }
      set {
        streamName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry> _repeated_records_codec
        = pb::FieldCodec.ForMessage(18, global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry.Parser);
    private readonly pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry> records_ = new pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntry> Records {
      get { return records_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRecordsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRecordsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StreamName != other.StreamName) return false;
      if(!records_.Equals(other.records_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StreamName.Length != 0) hash ^= StreamName.GetHashCode();
      hash ^= records_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StreamName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StreamName);
      }
      records_.WriteTo(output, _repeated_records_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StreamName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StreamName);
      }
      size += records_.CalculateSize(_repeated_records_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRecordsRequest other) {
      if (other == null) {
        return;
      }
      if (other.StreamName.Length != 0) {
        StreamName = other.StreamName;
      }
      records_.Add(other.records_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            StreamName = input.ReadString();
            break;
          }
          case 18: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutRecordsRequestEntry : pb::IMessage<PutRecordsRequestEntry> {
    private static readonly pb::MessageParser<PutRecordsRequestEntry> _parser = new pb::MessageParser<PutRecordsRequestEntry>(() => new PutRecordsRequestEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRecordsRequestEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntry(PutRecordsRequestEntry other) : this() {
      data_ = other.data_;
      explicitHashKey_ = other.explicitHashKey_;
      partitionKey_ = other.partitionKey_;
      partitionId_ = other.partitionId_;
      ExtendedInfo = other.extendedInfo_ != null ? other.ExtendedInfo.Clone() : null;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntry Clone() {
      return new PutRecordsRequestEntry(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "explicitHashKey" field.</summary>
    public const int ExplicitHashKeyFieldNumber = 4;
    private string explicitHashKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExplicitHashKey {
      get { return explicitHashKey_; }
      set {
        explicitHashKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "partitionKey" field.</summary>
    public const int PartitionKeyFieldNumber = 5;
    private string partitionKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PartitionKey {
      get { return partitionKey_; }
      set {
        partitionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "partitionId" field.</summary>
    public const int PartitionIdFieldNumber = 6;
    private string partitionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PartitionId {
      get { return partitionId_; }
      set {
        partitionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "extendedInfo" field.</summary>
    public const int ExtendedInfoFieldNumber = 7;
    private global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo extendedInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo ExtendedInfo {
      get { return extendedInfo_; }
      set {
        extendedInfo_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 29;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRecordsRequestEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRecordsRequestEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (ExplicitHashKey != other.ExplicitHashKey) return false;
      if (PartitionKey != other.PartitionKey) return false;
      if (PartitionId != other.PartitionId) return false;
      if (!object.Equals(ExtendedInfo, other.ExtendedInfo)) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (ExplicitHashKey.Length != 0) hash ^= ExplicitHashKey.GetHashCode();
      if (PartitionKey.Length != 0) hash ^= PartitionKey.GetHashCode();
      if (PartitionId.Length != 0) hash ^= PartitionId.GetHashCode();
      if (extendedInfo_ != null) hash ^= ExtendedInfo.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (ExplicitHashKey.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ExplicitHashKey);
      }
      if (PartitionKey.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PartitionKey);
      }
      if (PartitionId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(PartitionId);
      }
      if (extendedInfo_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ExtendedInfo);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(232, 1);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (ExplicitHashKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExplicitHashKey);
      }
      if (PartitionKey.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartitionKey);
      }
      if (PartitionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PartitionId);
      }
      if (extendedInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExtendedInfo);
      }
      if (Timestamp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRecordsRequestEntry other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.ExplicitHashKey.Length != 0) {
        ExplicitHashKey = other.ExplicitHashKey;
      }
      if (other.PartitionKey.Length != 0) {
        PartitionKey = other.PartitionKey;
      }
      if (other.PartitionId.Length != 0) {
        PartitionId = other.PartitionId;
      }
      if (other.extendedInfo_ != null) {
        if (extendedInfo_ == null) {
          extendedInfo_ = new global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo();
        }
        ExtendedInfo.MergeFrom(other.ExtendedInfo);
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            Data = input.ReadBytes();
            break;
          }
          case 34: {
            ExplicitHashKey = input.ReadString();
            break;
          }
          case 42: {
            PartitionKey = input.ReadString();
            break;
          }
          case 50: {
            PartitionId = input.ReadString();
            break;
          }
          case 58: {
            if (extendedInfo_ == null) {
              extendedInfo_ = new global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsRequestEntryExtendedInfo();
            }
            input.ReadMessage(extendedInfo_);
            break;
          }
          case 232: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutRecordsRequestEntryExtendedInfo : pb::IMessage<PutRecordsRequestEntryExtendedInfo> {
    private static readonly pb::MessageParser<PutRecordsRequestEntryExtendedInfo> _parser = new pb::MessageParser<PutRecordsRequestEntryExtendedInfo>(() => new PutRecordsRequestEntryExtendedInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRecordsRequestEntryExtendedInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntryExtendedInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntryExtendedInfo(PutRecordsRequestEntryExtendedInfo other) : this() {
      fileName_ = other.fileName_;
      deliverDataId_ = other.deliverDataId_;
      endFlag_ = other.endFlag_;
      seqNum_ = other.seqNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsRequestEntryExtendedInfo Clone() {
      return new PutRecordsRequestEntryExtendedInfo(this);
    }

    /// <summary>Field number for the "fileName" field.</summary>
    public const int FileNameFieldNumber = 8;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deliverDataId" field.</summary>
    public const int DeliverDataIdFieldNumber = 9;
    private string deliverDataId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DeliverDataId {
      get { return deliverDataId_; }
      set {
        deliverDataId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endFlag" field.</summary>
    public const int EndFlagFieldNumber = 10;
    private bool endFlag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EndFlag {
      get { return endFlag_; }
      set {
        endFlag_ = value;
      }
    }

    /// <summary>Field number for the "seqNum" field.</summary>
    public const int SeqNumFieldNumber = 11;
    private long seqNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SeqNum {
      get { return seqNum_; }
      set {
        seqNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRecordsRequestEntryExtendedInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRecordsRequestEntryExtendedInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (DeliverDataId != other.DeliverDataId) return false;
      if (EndFlag != other.EndFlag) return false;
      if (SeqNum != other.SeqNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (DeliverDataId.Length != 0) hash ^= DeliverDataId.GetHashCode();
      if (EndFlag != false) hash ^= EndFlag.GetHashCode();
      if (SeqNum != 0L) hash ^= SeqNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FileName);
      }
      if (DeliverDataId.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(DeliverDataId);
      }
      if (EndFlag != false) {
        output.WriteRawTag(80);
        output.WriteBool(EndFlag);
      }
      if (SeqNum != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(SeqNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (DeliverDataId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeliverDataId);
      }
      if (EndFlag != false) {
        size += 1 + 1;
      }
      if (SeqNum != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SeqNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRecordsRequestEntryExtendedInfo other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.DeliverDataId.Length != 0) {
        DeliverDataId = other.DeliverDataId;
      }
      if (other.EndFlag != false) {
        EndFlag = other.EndFlag;
      }
      if (other.SeqNum != 0L) {
        SeqNum = other.SeqNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 66: {
            FileName = input.ReadString();
            break;
          }
          case 74: {
            DeliverDataId = input.ReadString();
            break;
          }
          case 80: {
            EndFlag = input.ReadBool();
            break;
          }
          case 88: {
            SeqNum = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutRecordsResult : pb::IMessage<PutRecordsResult> {
    private static readonly pb::MessageParser<PutRecordsResult> _parser = new pb::MessageParser<PutRecordsResult>(() => new PutRecordsResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRecordsResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResult(PutRecordsResult other) : this() {
      failedRecordCount_ = other.failedRecordCount_;
      records_ = other.records_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResult Clone() {
      return new PutRecordsResult(this);
    }

    /// <summary>Field number for the "failedRecordCount" field.</summary>
    public const int FailedRecordCountFieldNumber = 21;
    private int failedRecordCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FailedRecordCount {
      get { return failedRecordCount_; }
      set {
        failedRecordCount_ = value;
      }
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 22;
    private static readonly pb::FieldCodec<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry> _repeated_records_codec
        = pb::FieldCodec.ForMessage(178, global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry.Parser);
    private readonly pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry> records_ = new pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.PutRecordsResultEntry> Records {
      get { return records_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRecordsResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRecordsResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FailedRecordCount != other.FailedRecordCount) return false;
      if(!records_.Equals(other.records_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FailedRecordCount != 0) hash ^= FailedRecordCount.GetHashCode();
      hash ^= records_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FailedRecordCount != 0) {
        output.WriteRawTag(168, 1);
        output.WriteInt32(FailedRecordCount);
      }
      records_.WriteTo(output, _repeated_records_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FailedRecordCount != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(FailedRecordCount);
      }
      size += records_.CalculateSize(_repeated_records_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRecordsResult other) {
      if (other == null) {
        return;
      }
      if (other.FailedRecordCount != 0) {
        FailedRecordCount = other.FailedRecordCount;
      }
      records_.Add(other.records_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 168: {
            FailedRecordCount = input.ReadInt32();
            break;
          }
          case 178: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PutRecordsResultEntry : pb::IMessage<PutRecordsResultEntry> {
    private static readonly pb::MessageParser<PutRecordsResultEntry> _parser = new pb::MessageParser<PutRecordsResultEntry>(() => new PutRecordsResultEntry());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PutRecordsResultEntry> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResultEntry() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResultEntry(PutRecordsResultEntry other) : this() {
      shardId_ = other.shardId_;
      sequenceNumber_ = other.sequenceNumber_;
      errorCode_ = other.errorCode_;
      errorMessage_ = other.errorMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PutRecordsResultEntry Clone() {
      return new PutRecordsResultEntry(this);
    }

    /// <summary>Field number for the "shardId" field.</summary>
    public const int ShardIdFieldNumber = 23;
    private string shardId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShardId {
      get { return shardId_; }
      set {
        shardId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sequenceNumber" field.</summary>
    public const int SequenceNumberFieldNumber = 24;
    private string sequenceNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SequenceNumber {
      get { return sequenceNumber_; }
      set {
        sequenceNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errorCode" field.</summary>
    public const int ErrorCodeFieldNumber = 25;
    private string errorCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorCode {
      get { return errorCode_; }
      set {
        errorCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 26;
    private string errorMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PutRecordsResultEntry);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PutRecordsResultEntry other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShardId != other.ShardId) return false;
      if (SequenceNumber != other.SequenceNumber) return false;
      if (ErrorCode != other.ErrorCode) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ShardId.Length != 0) hash ^= ShardId.GetHashCode();
      if (SequenceNumber.Length != 0) hash ^= SequenceNumber.GetHashCode();
      if (ErrorCode.Length != 0) hash ^= ErrorCode.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShardId.Length != 0) {
        output.WriteRawTag(186, 1);
        output.WriteString(ShardId);
      }
      if (SequenceNumber.Length != 0) {
        output.WriteRawTag(194, 1);
        output.WriteString(SequenceNumber);
      }
      if (ErrorCode.Length != 0) {
        output.WriteRawTag(202, 1);
        output.WriteString(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(210, 1);
        output.WriteString(ErrorMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShardId.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ShardId);
      }
      if (SequenceNumber.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SequenceNumber);
      }
      if (ErrorCode.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ErrorCode);
      }
      if (ErrorMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PutRecordsResultEntry other) {
      if (other == null) {
        return;
      }
      if (other.ShardId.Length != 0) {
        ShardId = other.ShardId;
      }
      if (other.SequenceNumber.Length != 0) {
        SequenceNumber = other.SequenceNumber;
      }
      if (other.ErrorCode.Length != 0) {
        ErrorCode = other.ErrorCode;
      }
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 186: {
            ShardId = input.ReadString();
            break;
          }
          case 194: {
            SequenceNumber = input.ReadString();
            break;
          }
          case 202: {
            ErrorCode = input.ReadString();
            break;
          }
          case 210: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRecordsRequest : pb::IMessage<GetRecordsRequest> {
    private static readonly pb::MessageParser<GetRecordsRequest> _parser = new pb::MessageParser<GetRecordsRequest>(() => new GetRecordsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRecordsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsRequest(GetRecordsRequest other) : this() {
      shardIterator_ = other.shardIterator_;
      limit_ = other.limit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsRequest Clone() {
      return new GetRecordsRequest(this);
    }

    /// <summary>Field number for the "shardIterator" field.</summary>
    public const int ShardIteratorFieldNumber = 12;
    private string shardIterator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShardIterator {
      get { return shardIterator_; }
      set {
        shardIterator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 13;
    private int limit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Limit {
      get { return limit_; }
      set {
        limit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRecordsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRecordsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShardIterator != other.ShardIterator) return false;
      if (Limit != other.Limit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ShardIterator.Length != 0) hash ^= ShardIterator.GetHashCode();
      if (Limit != 0) hash ^= Limit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShardIterator.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(ShardIterator);
      }
      if (Limit != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(Limit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShardIterator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShardIterator);
      }
      if (Limit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Limit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRecordsRequest other) {
      if (other == null) {
        return;
      }
      if (other.ShardIterator.Length != 0) {
        ShardIterator = other.ShardIterator;
      }
      if (other.Limit != 0) {
        Limit = other.Limit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 98: {
            ShardIterator = input.ReadString();
            break;
          }
          case 104: {
            Limit = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetRecordsResult : pb::IMessage<GetRecordsResult> {
    private static readonly pb::MessageParser<GetRecordsResult> _parser = new pb::MessageParser<GetRecordsResult>(() => new GetRecordsResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetRecordsResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsResult(GetRecordsResult other) : this() {
      nextShardIterator_ = other.nextShardIterator_;
      records_ = other.records_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetRecordsResult Clone() {
      return new GetRecordsResult(this);
    }

    /// <summary>Field number for the "nextShardIterator" field.</summary>
    public const int NextShardIteratorFieldNumber = 14;
    private string nextShardIterator_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NextShardIterator {
      get { return nextShardIterator_; }
      set {
        nextShardIterator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 16;
    private static readonly pb::FieldCodec<global::HuaweiCloud.DIS.Api.Protobuf.Record> _repeated_records_codec
        = pb::FieldCodec.ForMessage(130, global::HuaweiCloud.DIS.Api.Protobuf.Record.Parser);
    private readonly pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.Record> records_ = new pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.Record>();
    /// <summary>
    ///    int64 millisBehindLatest =15;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::HuaweiCloud.DIS.Api.Protobuf.Record> Records {
      get { return records_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetRecordsResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetRecordsResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NextShardIterator != other.NextShardIterator) return false;
      if(!records_.Equals(other.records_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NextShardIterator.Length != 0) hash ^= NextShardIterator.GetHashCode();
      hash ^= records_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (NextShardIterator.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(NextShardIterator);
      }
      records_.WriteTo(output, _repeated_records_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NextShardIterator.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NextShardIterator);
      }
      size += records_.CalculateSize(_repeated_records_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetRecordsResult other) {
      if (other == null) {
        return;
      }
      if (other.NextShardIterator.Length != 0) {
        NextShardIterator = other.NextShardIterator;
      }
      records_.Add(other.records_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 114: {
            NextShardIterator = input.ReadString();
            break;
          }
          case 130: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Record : pb::IMessage<Record> {
    private static readonly pb::MessageParser<Record> _parser = new pb::MessageParser<Record>(() => new Record());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Record> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::HuaweiCloud.DIS.Api.Protobuf.MessageReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record(Record other) : this() {
      partitionKey_ = other.partitionKey_;
      sequenceNumber_ = other.sequenceNumber_;
      data_ = other.data_;
      timestamp_ = other.timestamp_;
      timestampType_ = other.timestampType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Record Clone() {
      return new Record(this);
    }

    /// <summary>Field number for the "partitionKey" field.</summary>
    public const int PartitionKeyFieldNumber = 17;
    private string partitionKey_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PartitionKey {
      get { return partitionKey_; }
      set {
        partitionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sequenceNumber" field.</summary>
    public const int SequenceNumberFieldNumber = 18;
    private string sequenceNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SequenceNumber {
      get { return sequenceNumber_; }
      set {
        sequenceNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 19;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 27;
    private long timestamp_;
    /// <summary>
    ///	approximateArrivalTimestamp = 20;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "timestampType" field.</summary>
    public const int TimestampTypeFieldNumber = 28;
    private string timestampType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TimestampType {
      get { return timestampType_; }
      set {
        timestampType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Record);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Record other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PartitionKey != other.PartitionKey) return false;
      if (SequenceNumber != other.SequenceNumber) return false;
      if (Data != other.Data) return false;
      if (Timestamp != other.Timestamp) return false;
      if (TimestampType != other.TimestampType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PartitionKey.Length != 0) hash ^= PartitionKey.GetHashCode();
      if (SequenceNumber.Length != 0) hash ^= SequenceNumber.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (TimestampType.Length != 0) hash ^= TimestampType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PartitionKey.Length != 0) {
        output.WriteRawTag(138, 1);
        output.WriteString(PartitionKey);
      }
      if (SequenceNumber.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(SequenceNumber);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteBytes(Data);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(216, 1);
        output.WriteInt64(Timestamp);
      }
      if (TimestampType.Length != 0) {
        output.WriteRawTag(226, 1);
        output.WriteString(TimestampType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PartitionKey.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PartitionKey);
      }
      if (SequenceNumber.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(SequenceNumber);
      }
      if (Data.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Timestamp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (TimestampType.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(TimestampType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Record other) {
      if (other == null) {
        return;
      }
      if (other.PartitionKey.Length != 0) {
        PartitionKey = other.PartitionKey;
      }
      if (other.SequenceNumber.Length != 0) {
        SequenceNumber = other.SequenceNumber;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      if (other.TimestampType.Length != 0) {
        TimestampType = other.TimestampType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 138: {
            PartitionKey = input.ReadString();
            break;
          }
          case 146: {
            SequenceNumber = input.ReadString();
            break;
          }
          case 154: {
            Data = input.ReadBytes();
            break;
          }
          case 216: {
            Timestamp = input.ReadInt64();
            break;
          }
          case 226: {
            TimestampType = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
